package KonversiSuhu;




import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class KonvertSuhu extends javax.swing.JFrame {

    /**
     * Creates new form KonvertSuhu
     */
    public KonvertSuhu() {
        initComponents();
        ComboBoxSkalaAkhir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit", "Reamur", "Kelvin" }));
         // Tambahkan DocumentListener ke txtInput
        txtInput.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                convertTemperature();
            }
            public void removeUpdate(DocumentEvent e) {
                convertTemperature();
            }
            public void insertUpdate(DocumentEvent e) {
                convertTemperature();
            }
        });
        
        // Tambahkan listener untuk radio buttons
        buttonGroup1.add(Jfahreinheit);
        buttonGroup1.add(jCelcius);
        buttonGroup1.add(jReamur);
        buttonGroup1.add(jKelvin);
        
        Jfahreinheit.addActionListener(e -> convertTemperature());
        jCelcius.addActionListener(e -> convertTemperature());
        jReamur.addActionListener(e -> convertTemperature());
        jKelvin.addActionListener(e -> convertTemperature());
        
        // Tambahkan listener untuk combo box
        ComboBoxSkalaAkhir.addActionListener(e -> convertTemperature());
    }

    // Metode konversi yang dipisahkan
    private void convertTemperature() {
        if (txtInput.getText().trim().isEmpty()) {
            jTextField2.setText("");
            return;
        }
        
        try {
            double input = Double.parseDouble(txtInput.getText());
            double result = 0;
            String selectedInputScale = "";
            String outputScale = ComboBoxSkalaAkhir.getSelectedItem().toString();

            // Determine selected initial scale
            if (jCelcius.isSelected()) selectedInputScale = "Celsius";
            else if (Jfahreinheit.isSelected()) selectedInputScale = "Fahrenheit";
            else if (jReamur.isSelected()) selectedInputScale = "Reamur";
            else if (jKelvin.isSelected()) selectedInputScale = "Kelvin";
            else {
                jTextField2.setText("Pilih suhu awal!");
                return;
            }

            // Convert temperature
            switch (selectedInputScale) {
                case "Celsius":
                    if (outputScale.equals("Fahrenheit")) result = input * 9/5 + 32;
                    else if (outputScale.equals("Reamur")) result = input * 4/5;
                    else if (outputScale.equals("Kelvin")) result = input + 273.15;
                    else result = input; // To Celsius
                    break;

                case "Fahrenheit":
                    if (outputScale.equals("Celsius")) result = (input - 32) * 5/9;
                    else if (outputScale.equals("Reamur")) result = (input - 32) * 4/9;
                    else if (outputScale.equals("Kelvin")) result = (input - 32) * 5/9 + 273.15;
                    else result = input; // To Fahrenheit
                    break;

                case "Reamur":
                    if (outputScale.equals("Celsius")) result = input * 5/4;
                    else if (outputScale.equals("Fahrenheit")) result = input * 9/4 + 32;
                    else if (outputScale.equals("Kelvin")) result = input * 5/4 + 273.15;
                    else result = input; // To Reamur
                    break;

                case "Kelvin":
                    if (outputScale.equals("Celsius")) result = input - 273.15;
                    else if (outputScale.equals("Fahrenheit")) result = (input - 273.15) * 9/5 + 32;
                    else if (outputScale.equals("Reamur")) result = (input - 273.15) * 4/5;
                    else result = input; // To Kelvin
                    break;
            }

            // Display result
            jTextField2.setText(String.format("%.2f", result));

        } catch (NumberFormatException e) {
            jTextField2.setText("Input tidak valid");
        }
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Jfahreinheit = new javax.swing.JRadioButton();
        jCelcius = new javax.swing.JRadioButton();
        jReamur = new javax.swing.JRadioButton();
        jKelvin = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ComboBoxSkalaAkhir = new javax.swing.JComboBox<>();
        txtInput = new javax.swing.JTextField();
        Konversi = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Hasil = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Konvert Suhu");

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        buttonGroup1.add(Jfahreinheit);
        Jfahreinheit.setText("Fahreinheit");

        buttonGroup1.add(jCelcius);
        jCelcius.setText("Celcius");

        buttonGroup1.add(jReamur);
        jReamur.setText("Reamur");

        buttonGroup1.add(jKelvin);
        jKelvin.setText("Kelvin");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jLabel4.setText("PILIH SUHU YANG INGIN DI KONVERSI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jKelvin, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jReamur, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jfahreinheit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(Jfahreinheit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCelcius)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jReamur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jKelvin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        ComboBoxSkalaAkhir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celicus", "Fahreinheit", "Reamur", "Kelvin" }));

        Konversi.setText("Konvesi");
        Konversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KonversiActionPerformed(evt);
            }
        });

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jLabel2.setText("PILIH SUHU :");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel3.setText("INPUT NILAI SUHU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Konversi, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBoxSkalaAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(81, 81, 81))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ComboBoxSkalaAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Clear, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(Konversi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        Hasil.setBackground(new java.awt.Color(255, 153, 204));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 14)); // NOI18N
        jLabel1.setText("HASIL NILAI KONVERSI SUHU");

        javax.swing.GroupLayout HasilLayout = new javax.swing.GroupLayout(Hasil);
        Hasil.setLayout(HasilLayout);
        HasilLayout.setHorizontalGroup(
            HasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HasilLayout.createSequentialGroup()
                .addGroup(HasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HasilLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HasilLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HasilLayout.setVerticalGroup(
            HasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HasilLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Hasil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hasil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KonversiActionPerformed
         try {
            double input = Double.parseDouble(txtInput.getText());
            double result = 0;
            String selectedInputScale = "";
            String outputScale = ComboBoxSkalaAkhir.getSelectedItem().toString();

            // Determine selected initial scale
            if (jCelcius.isSelected()) selectedInputScale = "Celsius";
            else if (Jfahreinheit.isSelected()) selectedInputScale = "Fahrenheit";
            else if (jReamur.isSelected()) selectedInputScale = "Reamur";
            else if (jKelvin.isSelected()) selectedInputScale = "Kelvin";
            else {
                JOptionPane.showMessageDialog(this, "Pilih suhu awal!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Convert temperature
            switch (selectedInputScale) {
                case "Celsius":
                    if (outputScale.equals("Fahrenheit")) result = input * 9/5 + 32;
                    else if (outputScale.equals("Reamur")) result = input * 4/5;
                    else if (outputScale.equals("Kelvin")) result = input + 273.15;
                    else result = input; // To Celsius
                    break;

                case "Fahrenheit":
                    if (outputScale.equals("Celsius")) result = (input - 32) * 5/9;
                    else if (outputScale.equals("Reamur")) result = (input - 32) * 4/9;
                    else if (outputScale.equals("Kelvin")) result = (input - 32) * 5/9 + 273.15;
                    else result = input; // To Fahrenheit
                    break;

                case "Reamur":
                    if (outputScale.equals("Celsius")) result = input * 5/4;
                    else if (outputScale.equals("Fahrenheit")) result = input * 9/4 + 32;
                    else if (outputScale.equals("Kelvin")) result = input * 5/4 + 273.15;
                    else result = input; // To Reamur
                    break;

                case "Kelvin":
                    if (outputScale.equals("Celsius")) result = input - 273.15;
                    else if (outputScale.equals("Fahrenheit")) result = (input - 273.15) * 9/5 + 32;
                    else if (outputScale.equals("Reamur")) result = (input - 273.15) * 4/5;
                    else result = input; // To Kelvin
                    break;
            }

            // Display result
            jTextField2.setText(String.format("%.2f", result));

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan angka yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_KonversiActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonvertSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonvertSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonvertSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonvertSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonvertSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JComboBox<String> ComboBoxSkalaAkhir;
    private javax.swing.JPanel Hasil;
    private javax.swing.JRadioButton Jfahreinheit;
    private javax.swing.JButton Konversi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jCelcius;
    private javax.swing.JRadioButton jKelvin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jReamur;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
